### PR TITLE
don't error if package.json not found

### PR DESCRIPTION
**Pull request by mikestaub**
I ran into this error after bundling this module with webpack. It is a simple fix.

### CODE REVIEW

**Comment by Discordius** [comment]
I am also running into this problem and would love this to get merged (Meteor Galaxy doesn't copy over the package.json when deploying, so I am currently unable to use Timber).

**Comment by rdb** [comment]
Could this please be accepted ASAP and a new version of the package be released?  This is very urgent for me as it is blocking deployment.

**Comment by zsherman** [comment]
Sure thing, apologies for the delay—released in 3.1.3

**Comment by rdb** [comment]
It works well now, thanks a ton for the quick response!

**Pull request merged**
