### PR TITLE
v2.0.0

### LINKED ISSUE #11: Express middleware

### LINKED ISSUE #13: Enforce log line structure

### LINKED ISSUE #19: Messages logged using console.warn() get level set to error
Using `console.warn()` should set the `level` to `warn` instead of `error`.

### PR DESCRIPTION
**Pull request by ariamckinley**
The previous PR (#21) started extending past just express middleware, so I've merged all those changes into new branch in anticipation of the `2.0.0` release.

# Changes

## Express Middleware

timber-node `2.0.0` will ship with express middleware. This will allow you to automatically log all http events into rich structured logs that get sent to Timber automatically.

#### Usage:

```js
import timber from "timber";

timber.install({
  transport: new timber.transports.HTTPS('TIMBER_API_KEY')
});
```

#### Output Example:

```
Started GET "/awesome-api/endpoint"
Outgoing HTTP response 200 in 9ms
```

Which will show up in timber like

image

## Debug Logger

There is also now a debug logger built-in. This allow you to quickly debug any issues that may be occuring with the timber-node library. It's disabled by default, but will automatically be enabled once you set a stream for the debug logger to output to.

#### Usage:

```js
import timber from "timber"

timber.config.debug_logger = process.stdout

timber.install({
  transport: new timber.transports.HTTPS(process.env.TIMBER_API_KEY)
})
```

Or using a file stream

```js
import fs from "fs";
import timber from "timber"

timber.config.debug_logger = fs.createWriteStream('./debug.log', {flags: 'a'})

timber.install({
  transport: new timber.transports.HTTPS(process.env.TIMBER_API_KEY)
})
```

#### Example Output

```
[2017-06-07T19:35:43.419Z]: Initializing HTTPS transport stream
[2017-06-07T19:35:43.420Z]: Starting stream flusher
[2017-06-07T19:35:44.429Z]: Sending 1 log to stream
[2017-06-07T19:35:44.588Z]: logs.timber.io responded with 200
[2017-06-07T19:35:51.438Z]: Sending 3 logs to stream
[2017-06-07T19:35:51.537Z]: logs.timber.io responded with 200
[2017-06-07T19:35:53.441Z]: Sending 3 logs to stream
[2017-06-07T19:35:53.556Z]: logs.timber.io responded with 200
```

## Better Node Docs

The library is now adhering strictly to esdoc specifications, which means that there are now rich generated api docs. You can view them at any time from https://timberio.github.io/timber-node/

We will be working hard to also update both the readme and the [official timber docs](https://timber.io/docs/) with usage guides for the new release.

closes #11 
closes #19 
closes #13

### CODE REVIEW

**Comment by ariamckinley** [comment]
Yeah, I can use the `NODE_ENV` environment variable instead of `config.environment`

**Comment by ariamckinley** [comment]
Yeah I agree, there are rare times when someone will need a way to override the `NODE_ENV` in their script. But since 99% of users won't need to do that, I can keep the `environment` config value and default it to `NODE_ENV`.

Also to confirm, when using the http stream in the other libraries, does it always output the logs to stdout or change based on environment? Since it's possible to pass stdout as the stream, I wasn't sure if it made sense for it to output the logs to stdout when using an http stream.

**Comment by binarylogic** [comment]
Well to clarify, `config.environment` or `NODE_ENV` should not be used anywhere in the library. It should be `config.my_specific_setting`. This way the config file controls everything and that can easily be populated with environment variables if needed.

> Also to confirm, when using the http stream in the other libraries, does it always output the logs to stdout or change based on environment? Since it's possible to pass stdout as the stream, I wasn't sure if it made sense for it to output the logs to stdout when using an http stream.

It's all explicit. By default, no, but they can connect multiple backend log devices if they want. So the HTTP device is one stream, STDOUT is another, a file is another. It's up to them which ones they want to connect. This is all done in environment specific configuration files. For example, in rails, the installer will setup `production.rb` to log to the HTTP stream, but the user is welcome to go in there and also log to a file or STDOUT.

**Comment by ariamckinley** [comment]
Ah okay, that makes sense.

**Comment by binarylogic** [comment]
🎉 🔥 👍 💻

**Comment by zsherman** [comment]
giphy-9

**Pull request merged**
